version: '3'
services:
  server:
    build:
      context: ${QUORUM_ROOT}
      dockerfile: ${QUORUM_TOOLS_DIR}/server/Dockerfile
    command: python manage.py runserver_plus 0.0.0.0:8000
    container_name: django_server
    environment:
      WEB_APP: host.docker.internal
      DOCKER_TESTING_LOCAL_PG: ${DOCKER_TESTING_LOCAL_PG} # Allow using  the dockerized postgres db if desired
      USE_PROD_DB: ${USE_PROD_DB}  # only connect to the prod db if passed via environment variable
      USE_LOCAL_DB: ${USE_LOCAL_DB}  # only run server connected to dockerized postgres if passed via environment variable
    restart: unless-stopped
    volumes:
      - ${QUORUM_ROOT}:/code:delegated
    ports:
      - "8000:8000"
      - "9200:9200"
    stdin_open: true
    tty: true
    networks:
      - development-network
  frontend:
    build:
      context: ${QUORUM_ROOT}
      dockerfile: Dockerfile-frontend
    command: gulp --usingDocker=true
    container_name: frontend
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
        - ${QUORUM_ROOT}:/code:delegated
    networks:
      - development-network
  postgres:
    build:
      context: ${QUORUM_ROOT}
      dockerfile: Dockerfile-postgres-local
    container_name: postgres_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASS: "dockerizedpostgres"
    ports:
      - "5432:5432"
    networks:
      - development-network
  nginx:
    build:
      context: ${QUORUM_TOOLS_DIR}/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - development-network

networks:
  development-network:
    driver: bridge
