version: '3'
services:
  server:
    build:
      context: ${QUORUM_ROOT}
      dockerfile: Dockerfile-server
    command: python manage.py runserver_plus 0.0.0.0:8000
    container_name: django_server
    environment:
      WEB_APP: 127.0.0.1
      DOCKER_TESTING_LOCAL_PG: ${DOCKER_TESTING_LOCAL_PG} # Allow using  the dockerized postgres db if desired
      USE_PROD_DB: ${USE_PROD_DB}  # only connect to the prod db if passed via environment variable
      USE_LOCAL_DB: ${USE_LOCAL_DB}  # only run server connected to dockerized postgres if passed via environment variable
    restart: unless-stopped
    volumes:
      - ${QUORUM_ROOT}:/code
    ports:
      - "8000:8000"
      - "9200:9200"
    stdin_open: true
    tty: true
    network_mode: "host"
  frontend:
    build:
      context: ${QUORUM_ROOT}
      dockerfile: Dockerfile-frontend
    command: gulp --usingDocker=true
    container_name: frontend
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - ${QUORUM_ROOT}:/code
      - node_modules:/code/node_modules
      - shared_node_modules:/code/shared/node_modules
      - QuorumDesign_node_modules:/code/QuorumDesign/node_modules
  postgres:
    build:
      context: ${QUORUM_ROOT}
      dockerfile: Dockerfile-postgres-local
    container_name: postgres_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASS: "dockerizedpostgres"
    ports:
      - "5432:5432"
  nginx:
    build:
      context: ${QUORUM_TOOLS_DIR}/nginx
      dockerfile: Dockerfile
    container_name: nginx
    network_mode: "host"

volumes:
  node_modules:
  shared_node_modules:
  QuorumDesign_node_modules:

networks:
  development-network:
    driver: bridge
